name: Building a Docker action
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:    
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
      - name: container action run
        id: hello-world
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@adidas-jmpr'
      - name: Output
        run: echo "This action was executed at ${{ steps.hello-world.outputs.time}}
